main: fr.bakaaless.DJPlugin.plugin.DjPlugin
version: 0.0.1-ALPHA
name: DjStation
author: BakaAless
api-version: "1.15"
load: POSTWORLD
softdepend:
  - NoteBlockAPI
commands:
  djstation:
    usage: ""